name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Evaluation automatique
      id: evaluation-automatique
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Evaluation automatique
        setup-command: pip install -r requirements.txt pytest pandas
        command: pytest tests/test_auto_eval.py -v
        timeout: 10
        max-score: 55
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        EVALUATION-AUTOMATIQUE_RESULTS: "${{steps.evaluation-automatique.outputs.result}}"
      with:
        runners: evaluation-automatique
